# Generated by Django 4.1.5 on 2023-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_description_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="date", field=models.DateField(),
        ),
    ]
